# Literature Review

## Market Readiness and Applications

While XR has yet to provide consumers with a value proposition that is broadly compelling and sustainable,[^22-lit_review-1] the industrial, healthcare, and military markets have embraced its potential for cost savings and competitive advantage.

[^22-lit_review-1]: This claim may well be tested in 2024, with the recent introduction of Apple's Vision Pro, a state of the art video pass-through device, and Meta's Quest 3, which is positioned primarily as a VR device, but also offers video-pass through.

Across industry, where the primary barrier to adoption is return on investment (ROI), it is generally accepted that AR's essential connection to reality (e.g. guiding a surgeon's hand) can reduce costs. AR has improved learning rates, reduced errors, increased yields, improved quality, and enhanced designs. By enabling collaborative design, remote expert guidance, and enhanced monitoring, it has also improved the end-user experience [@azuma2019road]. In industrial settings HMDs are typically designed to support operators in an unobtrusive fashion, allowing them to focus on a task in the physical world, e.g. inspection, maintenance, repair, and order picking. In doing so they can reduce cognitive and/or physical load thru supplemental hands-free displays [@starner2015weara]. Manufacturing and healthcare are two industries that have most benefited from early engagement of this technology.

In manufacturing, supporting operators and repair technicians with digital work instructions has been a common application of AR research and development since the early 1990s [@azuma1994impro]. AR is a core component of I4.0 that allows intuitive, real-time access to contextually appropriate information. It provides the ideal visual interface for collaborative problem solving as described in Grieves' original vision for digital twins [@grieves2015digit]. Due to the many benefits described above, a 2020 study documented applications in operations, maintenance, quality control, safety management, design, visualization, logistics, and marketing [@oztemel2020liter]. XR shows particular promise as a source of innovative tools and technologies for training workers at a time when finding skilled labor is increasingly difficult due to high retirement rates, global expansion, and increasing specialization [@kress2020optic].

A compelling case study for the use of AR in manufacturing comes from the automotive sector, where its benefits can be leveraged across the entire product life cycle [@gay-bellile2015appli]. During design it reduces the need for and cost of physical mock-ups. AR complements the traditional design process, enhancing physical prototypes with virtual elements that can be accurately evaluated in real-world context. Prior to production, AR can reduce the impact and cost of factory planning. Operators can evaluate simulated workspace changes virtually integrated into the real environment without disturbing production or requiring a complete and accurate 3D model of the existing environment. During production AR can benefit tasks related to assembly, picking, and quality control by delivering instructions naturally, in the ideal context (what, when, where, how needed). AR allows the operator to remain focused on the work area while augmenting their perception with relevant data from sensors and/or information systems. Sales efforts benefit from AR's ability to communicate aspects of the vehicle that are not otherwise observable, (e.g. performance characteristics), or demonstrate unaccessible features (e.g. options for models not in inventory). Unlike other methods, the AR based approach retains accurate perception of dimensions, volumes, and other cues that are subtle but important to human perception. During the operation phase, AR can enhance the driver experience in many ways by visualizing system characteristics, highlighting potential dangers, aiding perception in degraded conditions, and augmenting instructional materials and support services.

In healthcare, XR has therapeutic and educational applications ranging from pain management and the diagnosis of mental disorders to medical decision-making and surgical support [@aqlan2020detec]. AR in various forms has been adopted by the medical industry to improve patient / procedure outcomes and safety while reducing radiation exposure, recovery time, and costs. It is a well-suited complement to the trend towards minimally invasive procedures, where access and vision are limited [@yaniv2015appli]. In those cases AR eliminates the need for surgeons to map preoperative data to the patient from an adjacent monitor. It allows direct cognition of the operator's movements relative to patient anatomy. This form of image-guided surgery is achieved by tracking the surgical instruments and visualizing them over preoperative data registered to the patient. The challenge, time, and error of these procedures are less than screen-based alternatives that require filtered cognition [@kersten-oertel2015augme]. Medical necessity will likely drive the adoption of wearable devices that include AR functionality. Conditions like diabetes and macular degeneration can be monitored and/or improved with such devices. Eye worn sensors are being developed to address both of these medical necessities by improving the user's perception [@barfield2015weara].

In the military market, where many of these technologies were first proven, there remains a strong and growing demand for custom XR hardware solutions. In addition to the traditional HMD / HUD systems common in fixed and rotary wing aircraft, there are efforts underway to outfit service members with AR devices that support their mission [@kress2020optic]. The US Army's IVAS (Integrated Visual Augmentation System) is the most ambitious current example. Originally awarded in March of 2021, IVAS is a \$22b partnership with Microsoft to improve "Soldier sensing, decision making, target acquisition, and target engagement" [@army2022ivas]. While these custom hardware solutions provide further evidence of XR's adoption and future, educational applications for XR in the military are more relevant to this work. The wide range of applications include training and briefing support for pilots [@alexander2019trans], maintainers, leaders [@clayton2020virtu], and officers [@millican2017virtu].

## Barriers to Adoption

XR, particularly AR/MR, is still relatively immature. Despite great potential, adoption is slowed by technical, market, and other important social and legal obstacles [@azuma2019road].

Among technical limitations, general concerns about usability and immaturity are commonly noted [@leonard2018holog]. Usability is primarily concerned with qualities of the application software, including user interface design, which are outside the scope of this work but obviously critical to the user experience and thus adoption. Technical immaturity relates to display fidelity (e.g. resolution, FOV, brightness, and contrast) and pictorial consistency. Of the later, robust tracking is the most fundamental. AR devices must provide accurate, stable tracking in a variety of environmental conditions [@azuma2016most; @gay-bellile2015appli]. Related to tracking, and of particular concern to OST AR devices, is occlusion. Accurate compositing and occlusion require an understanding of the structure and illumination of the real world scene. These so-called scene semantics also allow for advanced interactions that build meaningful connections with the world [@fischer2015visua; @azuma2017makin]. Finally, VAC mitigation techniques are necessary to eliminate it as a source of user discomfort in fixed focal length displays [@kress2020optic].

Over time, compounded incremental improvements promise to address many of the issues related to display fidelity and world tracking. Fast, accurate, universal eye tracking is premiering in the latest generation of XR devices, enabling other critical technologies. VAC mitigation methods that utilize gaze direction to perform discrete or continuous focus tuning should soon follow, along with foveated displays [@kress2020optic]. Scene semantics is an active area of research in the deep learning community, and promising methods are emerging [@roberts2021hyper]. Hard-edged occlusion in OST AR and multifocal displays still seem intractable with modern optical designs. Future advancements will likely rely on innovative methods, including light field and digital holographic displays that allow for layered or even per-pixel scene depth [@kress2020optic]. Until then, tradeoffs guided by human factors and a deep understanding of customer needs will be required to deliver solutions with optimal product-market fit.

Meanwhile, market considerations will limit adoption, even for XR systems that are "good enough" for today. Key among those are interoperability, standards, validation, metrics, organizational readiness, and access to content. Interoperability promotes open and/or standardized interfaces between systems. Commercial XR solutions are frequently built on stacks of interconnected technology that rely on other systems for data, etc. As such, interoperability is essential to the development of reliable, cost effective systems [@gay-bellile2015appli]. Interoperability depends heavily on the emergence of standards created to promote and enable it.

Here, standards is a broadly interpreted term. It includes publications from "standards bodies" like UL, ISO, ANSI, and NIST; similar publications from professional organizations; written frameworks that guide organizational processes and decision-making; and software frameworks, including APIs, libraries, or stacks that facilitate development. Together, these standards provide informational scaffolding, development support, tools, and even legal cover that many organizations need to reduce uncertainty and ease adoption. Relevant examples include the UL 8400 safety standard [@ul2022xr8400], IEEE 1589 AR Learning Experience Model [@ieee2020ieee], ETSI's Augmented Reality Framework [@etsi2022arf], and Microsoft's Mixed Reality Toolkit [@ms2022mrtk].

Validation and metrics both relate to demonstrating the claimed benefit of these systems. For industrial applications, adoption depends on quantifying the system value in terms of ROI and/or other metrics. Domain-specific modeling methods and evaluation metrics are needed to facilitate direct assessment and comparison of these systems [@kersten-oertel2015augme]. Organizational readiness is an overall assessment of a company's ability to adopt an XR solution. It includes considerations that are both cultural (e.g. leadership, attitude, risk tolerance) and practical (e.g. budget, goals, capacity) in nature [@cook2019chall]. In part it is a measure of how well equipped the organization is to recognize and leverage the innovative benefits of XR, along with their willingness and ability to adapt to them [@leonard2018holog]. The final market consideration is access to content. At this stage of adoption, most industrial XR systems will be custom applications, with few consumer-off-the-shelf (COTS) solutions. That said, software frameworks are available that enable low / no-code alternatives for common application types. Also, there is a growing network of specialized development studios and value-added resellers available for XR development.

Important other social and legal barriers to XR adoption exist, most related to social comfort. Issues related to privacy and wearer's rights, censorship / disinformation / propaganda, driving with headsets, medical regulations, and related liabilities is a partial list of potential impediments [@barfield2015weara]. While important to consider in the context of XR adoption, this category is outside the scope of this work.

## Development Frameworks

In order to address many of the barriers identified above, a number of frameworks have been proposed to guide the specification, design, and implementation of XR solutions. Relevant works are summarized below, listed in order of publication date by category.

### Specification

@palmarini2017innov proposes a questionnaire based strategic decision making tool to guide the selection of AR systems for maintenance applications. The authors noted that these selections are challenging, with many considerations and a fragmented market of hardware and software solutions. Developed 30 questions, grouped into four questionnaires, based on the analysis of AR system characteristics described in related papers. Each questionnaire is designed to address the main hardware, software, and content choices involved, along with the overall suitability of an AR based solution. The author notes that the approach is not validated, does not address economic or ergonomic considerations, and does not generalize to other applications. Additionally, the resulting recommendations are general in nature and exclude VR and MR options.

### Design

@borsci2015empir describes the importance of alignment between training objectives, contents, method, and expected outcomes, along with the criteria used to evaluate those outcomes, in program design. This alignment is considered essential in the field of training assessment but usually overlooked in VR/AR studies. The authors found that experimental methods ignored important factors, did not employ standardized instruments, and failed to consider organizational or environmental needs. As a result, most studies are not reliable or generalizable. They concluded that a common framework is needed to address these issues in the design and assessment of XR training systems.

@taylor2021form proposes a framework for adapting live training events to distance learning via immersive environments. Flow Driven Learning Experience Design (FLXD) integrates flow and transactional distance theories into Kolb's experiential learning model. FLXD describes how the designer can combine traditional and immersive learning methods in a way that best meets the unique needs in each of ELT's four stages. Taylor's work was designed to meet the needs of the large, diverse population of learners typical in military training programs.

### Implementation

@longo2017smart details SOPHOS-MS, a methodological framework and reference implementation for augmented operators in I4.0 based on Lee's 5C architecture. Their framework adopts a human-centered approach wherein the operator is essential to the optimal integration of real and virtual assets. By providing real time feedback, support, and access to the IT knowledge-base, SOPHOS-MS extends operator capabilities. This is accomplished via a verbal natural language interface using a variety of XR hardware. Their approach is suitable for a both on-line and off-line purposes, including training, collaboration, and support. Tests of this versatile implementation showed that operators trained with it outperform traditionally-trained counterparts throughout a two week period of use.

@geng2020syste notes that industrial AR adoption is hindered, in part, by its reliance on custom software that is rarely reusable or flexible. The authors propose an adaptive no-code authoring system that allows end users to quickly customize and deploy ARWI (AR work instructions). The structure of their system enhances its adaptability to user needs, training environments, work processes, and system configurations. Its data driven design and form-based authoring tool are flexible, modular, and easily extensible. A collaborative implementation approach ensures that process requirements are accurately portrayed. Authoring tasks alternate between engineers and operators as each ARWI moves through four stages of development. Together, these features, and many more described therein, provide an agile alternative to rigid systems bottlenecked by their reliance on experienced developers.

@enricoandrea2021minim identified a lack of standards for the design of AR work instructions, without which choices are based on personal preference. This can lead to unnecessarily complex visuals that negatively impact cost and performance without improving the user experience. The authors proposed a standard process for AR work instruction design that conveys only the information required to accomplish a task, considering real objects involved, end-user needs, and task complexity. Experiments confirmed this "minimal AR" approach did not degrade any measured variable of user performance for various levels of task complexity.

## Assessment

Here, we review literature related to the assessment of XR systems, including well-known frameworks and popular instruments.

### Frameworks

@kersten-oertel2015augme described their DVV Taxonomy for describing AR image-guided surgical (IGS) systems, and proposed a framework for AR IGS assessment. DVV is an acronym of the three components identified in the taxonomy: data, visualization processing, and view. Those components, their classes and subclasses, and the relationships between them are considered at each step of the surgical scenario. The framework assesses AR IGS systems based on technical parameters, reliability, surgical performance, patient outcomes, economics, and social / legal / ethical aspects of use. Each component is evaluated in terms of the primary components of the operating room environment - surgeon, patient, and IGS system - and the relationships between them.

@jetter2018augme identified key performance indicators (KPIs) that influence user acceptance of AR for industrial applications. From a list of 16 candidate KPIs identified in a structured literature review and semi-structured expert interviews, the authors identified reduction of time and errors, spatial representation of contextual information, cognitive workload, and ease of use as the most predominant and suitable factors to study. Hypothesizing that the perceived usefulness of AR is influenced by those factors, a theoretical framework based on the Technology Acceptance Model (TAM) was developed to evaluate their effects on user attitudes and intentions. Their qualitative study found that all four KPIs had a positive role in users' perceived usefulness of AR, and thus their attitude towards and intent to use it. Despite that positive outcome, they also found that users are not yet convinced of AR's benefits, suggesting the importance of clear and convincing use cases.

@masood2019augme identify factors that influence the success of industrial AR using a research model based on the Technology, Organization, and Environment (TOE) for the adoption and implementation of innovation. Where implementation success (IS) is often measured in the literature by measures of worker performance improvement, here it refers to the benefits received by the company and their willingness to make further investments. Quantitative analysis found technological considerations, including system configuration along with technology hardware readiness and compatibility, and organizational fit had the most impact on IS. Their study also included a qualitative survey, which identified important challenges to IS. Together, these results provide a valuable, cohesive, and holistic depiction of success factors.

The following year @masood2020adopt extended their prior research with 22 experiments conducted in an industrial setting and designed to identify challenges and success factors for IAR adoption. Using a combination of quantitative and qualitative analysis, the authors found that user acceptance, system stability, and organizational fit were the primary factors for success. Likewise, user rejection, system incompatibilities, technical maturity, and content creation issues were the main challenges. These findings can help guide strategic planning and requirements development for new IAR initiatives. In addition, the study gathered diverse industry feedback related to each context of the TOE model. A key implication of this study is that the relative importance of technological and organizational considerations vary, with the later are more relevant in industry.

@danielsson2020augme developed and applied a framework to assess the state of AR for industrial assembly applications. From a manufacturing engineering perspective, the authors considered authoring, infrastructure, and validation. Technical maturity concerns focused on the readiness levels (TRLs) of available devices. Key requirements and enabling technologies were described. From both perspectives, AR is rapidly improving but still only suitable for limited usage. The authors identified a need for strategic decision-making guidelines for the integration of these systems. Such guidelines should need to be validated and account for economic considerations.

### Instruments

@witmer1998measu *Presence Questionnaire* (PQ) consists of 32 items and measures the degree of presence experienced in a virtual environment. The same publication describes the Immersive Tendencies Questionnaire (ITQ) which measures the tendency of an individual towards immersion with 29 items. Both instruments use a seven-point scale where the endpoints are anchored by opposing descriptors (e.g. not compelling / very compelling).

@jackson1996devel *Flow State Scale* (FSS) is a 36 item instrument used to measure nine dimensions of the flow state described by Csikszentmihályi. It uses a 5-point Likert-type scale anchored with strongly disagree / strongly agree descriptors.

@kennedy1993simul derived the *Simulator Sickness Questionnaire* (SSQ) from a prior instrument intended to measure real-world motion sickness. Differences in the origin, type, and severity of SSQ symptoms demanded it. Users self-report the presence of 16 symptoms ranging from general discomfort to nausea. Each symptom is measured on a scale of none, slight, moderate, severe. Three principal factors of SSQ are interpreted as clusters of oculomotor, disorientation, and nausea symptoms.

The *NASA Task Load Index* (TLX) [@hart2006tlx] has been used to estimate workload for almost 40 years. It assesses overall task workload based on the magnitude of mental, physical, and mental demands imposed by the task, the operator's emotional response to those demands (effort, frustration), and their perceived ability to meet them (performance). These six factors are weighted based on the factors each subject feels best describe the workload associated with the task under study.

## XR in Manufacturing

Here we focus on case studies that evaluate the effectiveness of XR assisted ("augmented") instruction for manufacturing operations.

INSERT NEW LIT REVIEW MATERIAL HERE

...

## Summary of Findings

In light of this comprehensive review of existing literature, it is evident that the integration of XR technologies, particularly AR/MR, has potential to transform manufacturing assembly tasks. Successfully realizing that potential depends, in part, on the availability of frameworks to support sound decision making from the onset. Ideally, those frameworks should serve to align all aspects of the system's design with the business objectives [@borsci2015empir]. They should consider user needs related to usability and benefits to deliver a value proposition that is compelling to end users [@jetter2018augme]. They also should address technology and organizational issues that threaten short and long term success (ROI and the likelihood of further investment, respectively) [@masood2019augme]. Priority should be given to user acceptance, technical integration, organizational fit, and content creation considerations [@masood2020adopt]. Finally, these guidelines should be validated [@danielsson2020augme].

Though the need is established for strategic decision making guidelines as described above, few such frameworks were found in the literature. Of particular note is the questionnaire based approach proposed by @palmarini2017innov. Though innovative, it falls well short of the idealized requirements. It fails to account for economic considerations, is not validated, covers only AR devices, and its recommendations are general and out of date.

TIE BACK TO NEW LITERATURE - ABSENCE OF PROOF OF VALUE PROP

*...in spite of all the promising indicators, we find insufficient evidence to clearly quantify the extent to which augmented training can accelerate learning, improve operator performance, or increase retention in manufacturing applications. Without such evidence, the ROI for these systems remains unclear.*
