book:
  title: "Augmented vs. Traditional Instruction in Manufacturing Assembly"
  subtitle: "An Affordance-Based, Multi-Modal Assessment of Learning, Recall, and Retention"
  author: "Danny J. O'Leary"
  date: today
  chapters:
    - index.qmd
  # - _chaps/21-intro.qmd
  # - _chaps/22-lit_review.qmd
  # - _chaps/23-prob_statement.qmd
    - _chaps/24-methods.qmd
  # - _chaps/25-results.qmd
  # - _chaps/25a-h1a.qmd
  # - _chaps/25b-h1b.qmd
  # - _chaps/25c-h1c.qmd
  # - _chaps/25d-h2.qmd
  # - _chaps/25d-h3.qmd
  # - _chaps/26-conclusions.qmd
  # - _chaps/27-colophon.qmd
  # - _chaps/28-references.qmd
  # appendices:
    - _apps/32b-contributions.qmd
  #  - _apps/33c-s1conduct.qmd
  #  - _apps/34d-s2conduct.qmd
    - _apps/35e-videotools.qmd
    - _apps/36f-videoproc.qmd
  #  - _apps/37g-datadict.qmd
    - _apps/38h-dataorg.qmd
    - _apps/31a-irb.qmd
