project:
  type: book

book:
  title: "My Dissertation"
  author: "My Name"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrbook
    classoption: ["onepage", "openany"]




