# Quarto project - AU dissertation template
# initially based on new Quarto Book project
# uses titlepages v1 academic-static templates

project:
### Project reference: https://quarto.org/docs/reference/projects/options.html
# Main
  ## not used for filename:
  title: "Project Title"
  type: book
  output-dir: manuscript
# Other: Preview, Serve

book:
### Book reference: https://quarto.org/docs/reference/projects/books.html
# Book-specific project options
  title: "Book Title"
  subtitle: "Book Subtitle"
  author: "My Name"
  date: today
  chapters:
    ## index.qmd unused / empty, but error when removed...
    ## ERROR: Book contents must include a home page (e.g. index.md)
    - index.qmd
    - 21-intro.qmd
    - 22-lit_review.qmd
    - 23-prob_statement.qmd
    - 24-methods.qmd
    - 25-results.qmd
    - 26-conclusions.qmd
    - 27-references.qmd
  appendices:
    - 31-firstapp.qmd
# Other: Navbar, Nav Items, Sidebar, Sidebar Tools, Footer, Search, Algolia, Social,
# Twitter Card, Open Graph, Hypothesis, Utterances, Giscus, Listings, Feed, About

bibliography: references.bib

format:
  pdf:
  ### PDF reference: https://quarto.org/docs/reference/formats/pdf.html
  # Title & Author - see book options
  # Format Options
    ## results in build error, missing packages:
    # pdf-engine-opt: -output-directory=work
  # Table of Contents
    toc: true
    toc-depth: 3
    toc-title: Table of Contents
    lof: true
    lot: true
  # Numbering
    number-sections: true
  # Fonts
    mainfont: Georgia
    monofont: Source Code Pro
    fontsize: 12pt
    ## stretches all lines, not just body paragraphs:
    # linestretch: 1.5
  # Colors
  # Layout
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    geometry:
      - margin=1in
      - bindingoffset=0.5in
      - heightrounded
  # Includes
    include-in-header:
      - "templates/in-header.tex"
  # Metadata
  # Rendering
    template-partials:
      - "templates/before-body.tex"
      - "11-titlepage.tex"
      - "12-abstract.tex"
      - "13-acknowledgements.tex"
# Other: Code, Execution, Figures, Tables, References, Footnotes, Citation,
# Language, Latexmx, Text Ouput
