# Quarto project - AU dissertation template
# initially based on new Quarto Book project
# uses titlepages v1 academic-static templates
project:
  type: book

book:
  title: "My Dissertation"
  author: "My Name"
  date: today
  chapters:
    ## index.qmd unused / empty, but error when removed...
    ## ERROR: Book contents must include a home page (e.g. index.md)
    - index.qmd
    - 1-intro.qmd
    - 2-lit_review.qmd
    - 3-prob_statement.qmd
    - 4-methods.qmd
    - 5-results.qmd
    - 6-conclusions.qmd
    - 7-references.qmd
  appendices:
    - a-firstapp.qmd

bibliography: references.bib

format:
  pdf:
  ### PDF options: https://quarto.org/docs/reference/formats/pdf.html
  # Title & Author - see book options
  # Format Options
    ## results in build error, missing packages:
    # pdf-engine-opt: -output-directory=work
  # Table of Contents
    toc: true
    toc-depth: 3
    toc-title: Table of Contents
    lof: true
    lot: true
  # Numbering
    number-sections: true
  # Fonts
    mainfont: Times New Roman
    monofont: Source Code Pro
    fontsize: 12pt
    ## stretches all lines, not just body paragraphs:
    # linestretch: 1.5
  # Colors
  # Layout
    documentclass: scrbook
    classoption: ["twoside=false", "open=any"]
    geometry:
      - margin=1in
      - bindingoffset=0.5in
      - heightrounded
  # Code
  # Execution
  # Figures
  # Tables
  # References
  # Footnotes
  # Citation
  # Language
  # Includes
    ## results in missing math symbols:
    # include-in-header:
    #   - "templates/in-header.tex"
  # Metadata
  # Rendering
    template-partials:
      - "templates/before-body.tex"
      - "templates/_titlepage.tex"
  # Latexmx
  # Text Ouput
