---
title: "R Notebook"
output: html_notebook
---

Load the XLSX file

```{r}
### load libraries
library(tidyverse)
library(readxl)
```

```{r}
### read and clean the demographic data

raw_demog_xls <- read_xlsx(
  "./data/i1_raw_data.xlsx",
  na = c("", "N/A"),
  sheet = "DEMO")

demog_xls <- raw_demog_xls |>
  janitor::clean_names() |>
  # only use time information from trial_time column 
  mutate(trial_time = hms::as_hms(trial_time)) |>
  # combine date and time columns as single datetime and drop original cols
  mutate(trial_datetime = trial_date + trial_time) |>
  select(-c("trial_date", "trial_time")) |>
  # move numeric cols to the front
  select(all_of(c("participant", "age", "height")), everything()) |>
  # convert most cols to factors
  mutate(across(-("participant":"height" | "notes"), as.factor)) |>
  glimpse()
```
```{r}
### read and clean the car error data

raw_exp_xls <- read_xlsx(
  "./data/i1_raw_data.xlsx",
  sheet = "EXP")

exp_xls <- raw_exp_xls |>
  janitor::clean_names() |>
    mutate(
    result = case_when(
      tolower(flag) == "c" ~ "comment",
      tolower(flag) == "i" ~ "incomplete",
      is.na(flag) ~ "complete",
      tolower(flag) == "r" ~ "retired"
    ),
    result = as.factor(result),
    flag = as.factor(flag)
  ) |>
  rename(e_car = car) |>
  replace_na(list(ce = 0, uce = 0, sel = 0, pos = 0, rot = 0, count = 0)) |>
  group_by(participant, phase, result) |>
  mutate(
    number = ifelse(result == "comment", 0, cumsum(result == result))
  ) |>
  ungroup() |>
  group_by(participant, phase) |>
  mutate(
    sequence = row_number() - 1  # have comments at sequence 0
  ) |>
  ungroup()

exp_xls <- exp_xls |>
  select(
    participant,
    phase,
    sequence,
    flag,
    result,
    number,
    e_car,
    ce,
    uce,
    sel,
    pos,
    rot,
    count,
    notes
  ) |>
  glimpse()

write.csv(exp_xls, "exp_xls.csv", row.names = FALSE)
```
Check that errors add up:
```{r}
all(exp_xls$uce == exp_xls$sel + exp_xls$pos + exp_xls$rot)
```

```{r}
### read and clean the car time data

col_names = c(
  "participant",
  "phase",
  "event",
  "start_time",
  "duration",
  "note"
)

raw_times_csv <- read_csv("./data/i1_times.csv", col_names=col_names)

times_csv <- raw_times_csv |>
  janitor::clean_names() |>
  mutate(
    description = event,
    event = str_extract(event, "[a-zA-Z]+"), # Extract the event type
    event = as.factor(tolower(event))
  ) |>
  group_by(participant, phase, event) |>
  mutate(
    number = row_number() # sequence number for each event type
  ) |>
  ungroup() |>
  group_by(participant, phase) |>
  mutate(
    sequence = row_number()
  ) |>
  ungroup()

times_csv <- times_csv |>
  select(
    participant,
    phase,
    sequence,
    description,
    event,
    number,
    start_time,
    duration,
    note
  ) |>
  glimpse()
```

```{r}
# library(gt)
 
car_data <- exp_xls |>
  right_join(
    times_csv,
    by = c("participant", "phase", "car" = "number")
    ) |>
  rename(
    e_notes = notes,
    t_notes = note,
#    t_flag = event,
    e_flag = flag
    ) |>
  mutate(e_flag = as.factor(e_flag))

car_data <- car_data |>
  left_join(
    demog_xls |> select(participant, treatment),
    by = "participant"
  )

# reorder columns
car_data <- car_data %>%
  select(
    participant,
    treatment,
    phase,
    sequence,
    description,
    event,
    number,
    start_time,
    duration,
    e_flag,
    ce,
    uce,
    sel,
    pos,
    rot,
    count,
    e_notes,
    t_notes
  )

# write.csv(car_data, "car_data.csv", row.names = FALSE)

# output table
# gt(car_data)
```


```{r}
### play with plots (EDA)

library(gtExtras)

exp_xls |>
  filter(phase == 1) |>
  gt_plt_summary()
```

