import xml.etree.ElementTree as ET
import textwrap
import re

try:
    from .path_config import DEFAULT_BOX_ROOT, resolve_box_root
except ImportError:
    from path_config import DEFAULT_BOX_ROOT, resolve_box_root


def convert_to_seconds(value, time_base):
    """convert timestamps generated by kyno into seconds"""
    # print("*** in convert_to_seconds\n")
    numerator, denominator = map(int, time_base.split("/"))
    return value / denominator * numerator


def generate_markdown_report(xml_file_path, box_root=DEFAULT_BOX_ROOT):
    """
    Generate a markdown report based on the content of the given XML file.

    Parameters:
    - xml_file_path (str): Path to the XML file.

    Returns:
    - str: Markdown formatted report.

    Example:
    >>> generate_markdown_report("path_to_file.xml")
    "## Descriptive Metadata Report for ... (and so on)"
    """
    # print("*** in generate_markdown_report\n")
    # Parse the XML content
    tree = ET.parse(xml_file_path)
    root = tree.getroot()

    # Extract general metadata
    metadata = {
        "url": root.find("descriptive-metadata/context-info/url").text,
        "size": root.find("descriptive-metadata/context-info/size").text,
        "last_modified": root.find(
            "descriptive-metadata/context-info/last-modified"
        ).text,
        "rating": root.find("descriptive-metadata/rating").text,
        "title": root.find("descriptive-metadata/title").text or "N/A",
    }

    # description element does not exist if not specified
    try:
        note_elem = root.find("descriptive-metadata/description").text
    except:
        note_elem = None

    metadata["note"] = note_elem if note_elem is not None else "N/A"
    # print(f"*** video description: {metadata['note']}")

    # Extract marker data
    markers = []
    for marker_elem in root.findall("descriptive-metadata/marker"):
        marker = {
            "id": marker_elem.find("id").text,
            "timestamp": (
                int(marker_elem.find("timestamp").text),
                marker_elem.find("timestamp").get("time-base"),
            ),
            "type": marker_elem.find("type").text,
            "title": marker_elem.find("title").text,
            "description": marker_elem.find("description").text or "N/A",
        }
        if marker_elem.find("duration") is not None:
            marker["duration"] = (
                int(marker_elem.find("duration").text),
                marker_elem.find("duration").get("time-base"),
            )
        markers.append(marker)

    # Convert the marker timestamps and durations to seconds
    for marker in markers:
        marker["timestamp"] = convert_to_seconds(*marker["timestamp"])
        if "duration" in marker:
            marker["duration"] = convert_to_seconds(*marker["duration"])

    # Split the markers into two lists: subclip markers and other markers
    subclip_markers = [marker for marker in markers if marker["type"] == "subclip"]
    other_markers = [marker for marker in markers if marker["type"] != "subclip"]

    video_file = metadata["url"].split("/")[-1]
    video_path = "/".join(metadata["url"].split("/")[-3:])
    box_root = resolve_box_root(box_root)

    # Generate markdown report
    report = {}
    report["metadata"] = (
        "> [!example]- **File Metadata**\n"
        f"> - **File Size**: {metadata['size']} bytes\n"
        f"> - **Last Modified**: {metadata['last_modified']}\n"
        f"> - **Title**: {metadata['title']}\n"
        f"> - **Rating**: {metadata['rating']}\n\n"
        f"**Open Video**: [{video_file}](file://{box_root + video_path})\n\n"
        f"### {metadata['title']} Observations\n"
    )

    # split notes from Kyno general properties into multiple lines
    # first use semicolon "convention" - used inconsistently
    # also split on newlines in the note data used, e.g. in 1001
    notes = re.split(r";|\n", metadata["note"])

    report["notes"] = ""
    for note in notes:
        note = note.strip()
        # for long individual notes, wrap the text
        if False:  # len(note) > 70:  disable for now, formatting not right
            wrapped_note = textwrap.wrap(note, width=70)
            report["notes"] += f"- {wrapped_note[0]}\n"
            # hanging indent for additional lines
            for line in wrapped_note[1:]:
                report["notes"] += f"  {line}\n"
        else:
            report["notes"] += f"- {note}\n"

    report["subclip_markers"] = (
        "\n### Subclip Markers\n\n"
        "| Name | Start Time (sec) | Duration (sec) | Description |\n"
        "|---|---|---|---|\n"
    )

    for marker in subclip_markers:
        report[
            "subclip_markers"
        ] += f"| {marker['title']} | {marker['timestamp']:.2f} | {marker['duration']:.2f} | {marker['description']} |\n"

    report["other_markers"] = "\n### Other Markers\n\n"

    if other_markers:
        report["other_markers"] += (
            "| Name | Type | Event Time (sec) | Description |\n" "|---|---|---|---|\n"
        )
        for marker in other_markers:
            report[
                "other_markers"
            ] += f"| {marker['title']} | {marker['type']} | {marker['timestamp']:.2f} | {marker['description']} |\n"
    else:
        report["other_markers"] += "No other markers found."

    return report, subclip_markers


if __name__ == "__main__":
    # testing...

    filenames = [
        "1001-Learn.xml",
        # "1027-Learn.xml",
        # "1027-Recall.xml",
        # "1033-Learn.xml",
        # "1033-Recall.xml",
        # "1041-Learn.xml",
        # "1041-Recall.xml",
        # "1050-Learn.xml",
        # "1050-Recall.xml",
    ]

    in_subdir = "test_input/"
    out_subdir = "test_output/"

    for filename in filenames:
        print(filename)
        fileroot = filename.split(".")[0]
        filepath = in_subdir + filename

        with open(out_subdir + fileroot + "-report.md", "w") as md:
            report = generate_markdown_report(filepath)
            md.write(report)
