import xml.etree.ElementTree as ET


def convert_to_seconds(value, time_base):
    """convert timestamps generated by kyno into seconds"""
    numerator, denominator = map(int, time_base.split("/"))
    return value / denominator * numerator


def generate_markdown_report(xml_file_path):
    """
    Generate a markdown report based on the content of the given XML file.

    Parameters:
    - xml_file_path (str): Path to the XML file.

    Returns:
    - str: Markdown formatted report.

    Example:
    >>> generate_markdown_report("path_to_file.xml")
    "## Descriptive Metadata Report for ... (and so on)"
    """

    # Parse the XML content
    tree = ET.parse(xml_file_path)
    root = tree.getroot()

    # Extract general metadata
    metadata = {
        "format_version": root.find("descriptive-metadata").get("format-version"),
        "version": root.find("descriptive-metadata/version").text,
        "url": root.find("descriptive-metadata/context-info/url").text,
        "size": root.find("descriptive-metadata/context-info/size").text,
        "last_modified": root.find(
            "descriptive-metadata/context-info/last-modified"
        ).text,
        "title": root.find("descriptive-metadata/title").text,
        "description": root.find("descriptive-metadata/description").text,
        "in_point": (
            int(root.find("descriptive-metadata/in-point").text),
            root.find("descriptive-metadata/in-point").get("time-base"),
        ),
        "out_point": (
            int(root.find("descriptive-metadata/out-point").text),
            root.find("descriptive-metadata/out-point").get("time-base"),
        ),
        "rating": root.find("descriptive-metadata/rating").text,
    }

    # Extract marker data
    markers = []
    for marker_elem in root.findall("descriptive-metadata/marker"):
        marker = {
            "id": marker_elem.find("id").text,
            "timestamp": (
                int(marker_elem.find("timestamp").text),
                marker_elem.find("timestamp").get("time-base"),
            ),
            "type": marker_elem.find("type").text,
            "title": marker_elem.find("title").text,
            "description": marker_elem.find("description").text or "N/A",
        }
        if marker_elem.find("duration") is not None:
            marker["duration"] = (
                int(marker_elem.find("duration").text),
                marker_elem.find("duration").get("time-base"),
            )
        markers.append(marker)

    # Convert the marker timestamps and durations to seconds
    for marker in markers:
        marker["timestamp"] = convert_to_seconds(*marker["timestamp"])
        if "duration" in marker:
            marker["duration"] = convert_to_seconds(*marker["duration"])

    # Split the markers into two lists: subclip markers and other markers
    subclip_markers = [marker for marker in markers if marker["type"] == "subclip"]
    other_markers = [marker for marker in markers if marker["type"] != "subclip"]

    # Generate markdown report
    report = f"""
## Descriptive Metadata Report for {metadata['title']}

**File Information**
- **Format Version**: {metadata['format_version']}
- **Version**: {metadata['version']}
- **File URL**: [{metadata['url']}]({metadata['url']})
- **File Size**: {metadata['size']} bytes
- **Last Modified**: {metadata['last_modified']}
- **Title**: {metadata['title']}
- **Description**: {metadata['description']}
- **In-point**: {metadata['in_point'][0]} seconds
- **Out-point**: {metadata['out_point'][0]} seconds
- **Rating**: {metadata['rating']}

### Subclip Markers
"""
    report += "| Name | Start Time (sec) | Duration (sec) | Description |\n"
    report += "|---|---|---|---|\n"
    for marker in subclip_markers:
        report += f"| {marker['title']} | {marker['timestamp']:.2f} | {marker['duration']:.2f} | {marker['description']} |\n"

    report += """
### Other Markers
"""
    report += "| Name | Type | Event Time (sec) | Description |\n"
    report += "|---|---|---|---|\n"
    for marker in other_markers:
        report += f"| {marker['title']} | {marker['type']} | {marker['timestamp']:.2f} | {marker['description']} |\n"

    return report


if __name__ == "__main__":
    filenames = [
        "1027-Learn.xml",
        "1027-Recall.xml",
        "1033-Learn.xml",
        "1033-Recall.xml",
        "1041-Learn.xml",
        "1041-Recall.xml",
        "1050-Learn.xml",
        "1050-Recall.xml",
    ]

    for filename in filenames:
        rootname = filename.split(".")[0]

        with open(rootname + "-report.md", "w") as md:
            report = generate_markdown_report(filename)
            md.write(report)
