"""process data, generate timing csv and combined participant reports"""

import csv
import glob
import logging
import os
import xml.etree.ElementTree as ET
from pathlib import Path

import typer
from rich import inspect
from rich import print as rprint
from rich.console import Console
from rich.logging import RichHandler
from rich.traceback import install

from rich.progress import Progress

install(show_locals=True)  # rich tracebacks
console = Console()  # rich console
progress = Progress(console=console)  # rich progress bar


REPORT_DIR = "/Users/djo/dev/au/au_diss/reports/"
XML_ROOT = "/Volumes/ThunderBay mini/Research Master/data/"


def init_logging():
    """
    Initializes a logger with a RichHandler for rich, colorful logging output.

    This function sets up the logging module to log messages at the INFO level,
    with a specific format and date format. The RichHandler is configured to
    not highlight any parts of the log messages automatically.

    Returns:
        logging.Logger: A logger instance configured for use throughout the application.
    """
    # console = Console()

    handler = RichHandler(console=console)
    handler.highlighter = None

    # Setup the logging module to use the RichHandler
    logging.basicConfig(
        level="INFO", format="%(message)s", datefmt="[%X]", handlers=[handler]
    )

    # override logging for packages
    logging.getLogger("gensim").setLevel(logging.WARNING)

    # return the logger object for global use
    return logging.getLogger("rich")


def convert_to_seconds(value, time_base):
    """convert timestamps generated by kyno into seconds"""
    # print("*** in convert_to_seconds\n")
    numerator, denominator = map(int, time_base.split("/"))
    return value / denominator * numerator


def extract_data_from_xml(xml_file_path: Path):
    """
    Extract data from the given XML file.

    Parameters:
    - xml_file_path (Path): Path to the XML file.

    Returns:
    - tuple of extracted data
    """
    # Parse the XML content
    tree = ET.parse(str(xml_file_path))
    root = tree.getroot()

    # Extract general metadata
    metadata = {
        "url": root.find("descriptive-metadata/context-info/url").text
        if root.find("descriptive-metadata/context-info/url") is not None
        else "N/A",
        "size": root.find("descriptive-metadata/context-info/size").text
        if root.find("descriptive-metadata/context-info/size") is not None
        else "N/A",
        "last_modified": root.find(
            "descriptive-metadata/context-info/last-modified"
        ).text
        if root.find("descriptive-metadata/context-info/last-modified") is not None
        else "N/A",
        "rating": root.find("descriptive-metadata/rating").text
        if root.find("descriptive-metadata/rating") is not None
        else "N/A",
        "title": root.find("descriptive-metadata/title").text
        if root.find("descriptive-metadata/title") is not None
        else "N/A",
    }

    # description element does not exist if not specified
    note_elem = (
        root.find("descriptive-metadata/description").text
        if root.find("descriptive-metadata/description") is not None
        else "N/A"
    )
    metadata["note"] = note_elem

    # Extract marker data
    markers = []
    for marker_elem in root.findall("descriptive-metadata/marker"):
        marker = {
            "id": marker_elem.find("id").text,
            "timestamp": (
                int(marker_elem.find("timestamp").text),
                marker_elem.find("timestamp").get("time-base"),
            ),
            "type": marker_elem.find("type").text,
            "title": marker_elem.find("title").text,
            "description": marker_elem.find("description").text or "N/A",
        }
        if marker_elem.find("duration") is not None:
            marker["duration"] = (
                int(marker_elem.find("duration").text),
                marker_elem.find("duration").get("time-base"),
            )
        markers.append(marker)

    # Convert the marker timestamps and durations to seconds
    for marker in markers:
        marker["timestamp"] = convert_to_seconds(*marker["timestamp"])
        if "duration" in marker:
            marker["duration"] = convert_to_seconds(*marker["duration"])

    # Split the markers into two lists: subclip markers and other markers
    subclip_markers = [marker for marker in markers if marker["type"] == "subclip"]
    other_markers = [marker for marker in markers if marker["type"] != "subclip"]

    return metadata, subclip_markers, other_markers


def generate_markdown_report(xml_file_path: Path):
    """
    Generate a markdown report based on the content of the given XML file.

    Parameters:
    - xml_file_path (Path): Path to the XML file.

    Returns:
    - str: Markdown formatted report.

    Example:
    >>> generate_markdown_report(Path("path_to_file.xml"))
    "## Descriptive Metadata Report for ... (and so on)"
    """
    metadata, subclip_markers, other_markers = extract_data_from_xml(xml_file_path)

    video_file = metadata["url"].split("/")[-1]
    video_path = "/".join(metadata["url"].split("/")[-3:])
    box_root = "/Users/djo/Box%20Sync/Tiger%20Motors%20Research%20Team%20Collaboration%20Files/Investigation%201%20Data%20Files/trial-data/"

    # Generate markdown report
    report = {}
    report["metadata"] = (
        "> [!example]- **File Metadata**\n"
        f"> - **File Size**: {metadata['size']} bytes\n"
        f"> - **Last Modified**: {metadata['last_modified']}\n"
        f"> - **Title**: {metadata['title']}\n"
        f"> - **Rating**: {metadata['rating']}\n\n"
        f"**Open Video**: [{video_file}](file://{box_root + video_path})\n\n"
        f"### {metadata['title']} Observations\n"
    )

    # split notes from Kyno general properties into multiple lines
    # first use semicolon "convention" - used inconsistently
    # also split on newlines in the note data used, e.g. in 1001
    notes = re.split(r";|\n", metadata["note"])

    report["notes"] = ""
    for note in notes:
        note = note.strip()
        # for long individual notes, wrap the text
        if False:  # len(note) > 70:  disable for now, formatting not right
            wrapped_note = textwrap.wrap(note, width=70)
            report["notes"] += f"- {wrapped_note[0]}\n"
            # hanging indent for additional lines
            for line in wrapped_note[1:]:
                report["notes"] += f"  {line}\n"
        else:
            report["notes"] += f"- {note}\n"

    report["subclip_markers"] = (
        "\n### Subclip Markers\n\n"
        "| Name | Start Time (sec) | Duration (sec) | Description |\n"
        "|---|---|---|---|\n"
    )

    for marker in subclip_markers:
        report[
            "subclip_markers"
        ] += f"| {marker['title']} | {marker['timestamp']:.2f} | {marker['duration']:.2f} | {marker['description']} |\n"

    report["other_markers"] = "\n### Other Markers\n\n"

    if other_markers:
        report["other_markers"] += (
            "| Name | Type | Event Time (sec) | Description |\n" "|---|---|---|---|\n"
        )
        for marker in other_markers:
            report[
                "other_markers"
            ] += f"| {marker['title']} | {marker['type']} | {marker['timestamp']:.2f} | {marker['description']} |\n"
    else:
        report["other_markers"] += "No other markers found."

    return report, subclip_markers


def extract_comments(md_file_path):
    """
    Extracts the h2 elements and underlying comments from hand-transcribed
    markdown notes (i.e., 1???.md). Ensures all notes are prefixed with "- ",
    and all h2 elements are preceded by one blank line.

    Args:
        md_file_path (Path): Path to the markdown file to extract comments from.

    Returns:
        md_out (list[str]): Processed lines.
    """
    logger.debug(f"*** Extracting comments from: {md_file_path}")

    with open(md_file_path, "r") as md_input:
        md_in = md_input.readlines()

    h2 = False
    md_out = []

    for line in md_in:
        if line.startswith("##"):
            h2 = True
        elif line.isspace():
            h2 = False
        if h2:
            if not line.startswith(("- ", "##")):
                # fix notes that aren't bulleted
                line = "- " + line
            if line.startswith("##"):
                line = "\n#" + line
            md_out.append(line)
            # print(line, end="")

    # rprint(md_out)
    return md_out


def main(REPORT_DIR: str = REPORT_DIR):
    logger.info("-- Entering main...")

    # for each trial report, extract script comments and feedback from hand-transcribed notes
    report_path = Path(REPORT_DIR)
    reports = sorted(report_path.glob("????.md"))
    logger.info(f"> Processing {len(reports)} reports...")

    logger.info(f"  > Extracting trial notes...")
    for report in reports:
        # e.g. if report = /Users/djo/dev/au/au_diss/reports/1001.md
        report_num = report.stem  # 1001
        report_dir = report.parent.name  # reports
        md_file = report.name  # 1001.md
        # md_file_path = str(report)  # /Users/djo/dev/au/au_diss/reports/1001.md

        trial_notes = extract_comments(report)

    # extract video annotation data from all XML files in the tree
    xml_path = Path(XML_ROOT)
    xml_data = {}
    xml_files = xml_path.rglob("*.xml")

    logger.info(f"  > Extracting XML data...")
    for xml_file in xml_files:
        metadata, subclip_markers, other_markers = extract_data_from_xml(xml_file)
        participant, phase = xml_file.stem.split("-")
        xml_data[(participant, phase)] = {
            "meta": metadata,
            "subclips": subclip_markers,
            "others": other_markers,
        }

    # save csv (xls?)
    # generate md reports, incorporating data from csv


if __name__ == "__main__":
    # set up logging
    logger = init_logging()
    logger.info("-- Logging setup complete.")

    typer.run(main)

"""
- generate_combined_reports: main entry point
    - main: combines md comments and extracted XML to generate report and csv
    - extract_comments: extracts hand-written comments from markdown files
- parse_xml: called by generate_combined_reports
    - convert_to_seconds: converts kyno timestamps into seconds
    - generate_markdown_report: extracts data from XML files, generates markdown report data
- process_video_tree: early attempt at report generation wrapper
    - first attempt at a report generation wrapper
    - searches dir tree, finds xmls files, calls generate_markdown_report, and writes that report
"""
